/* Simulation code for OET.Example.multibodyWECSingleDoF generated by the OpenModelica Compiler OpenModelica v1.24.3 (64-bit). */
#if !defined(OET_Example_multibodyWECSingleDoF__MODEL_H)
#define OET_Example_multibodyWECSingleDoF__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "OET.Example.multibodyWECSingleDoF_functions.h"

#define Modelica_Math_Vectors_interpolate_index 0
#define Modelica_Math_Vectors_length_index 1
#define Modelica_Math_Vectors_normalize_index 2
#define Modelica_Mechanics_MultiBody_Frames_Orientation_index 3
#define Modelica_Mechanics_MultiBody_Frames_axesRotationsAngles_index 4
#define Modelica_Mechanics_MultiBody_Frames_planarRotationAngle_index 5
#define Modelica_Mechanics_MultiBody_Frames_resolve2_index 6
#define Modelica_Mechanics_MultiBody_Frames_TransformationMatrices_from__nxy_index 7
#define Modelica_Mechanics_MultiBody_Frames_TransformationMatrices_planarRotation_index 8
#define Modelica_Mechanics_MultiBody_Frames_TransformationMatrices_resolve1_index 9
#define Modelica_Mechanics_MultiBody_Frames_TransformationMatrices_resolve2_index 10
#define Modelica_Utilities_Streams_readRealMatrix_index 11

extern void OET_Example_multibodyWECSingleDoF_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void OET_Example_multibodyWECSingleDoF_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void OET_Example_multibodyWECSingleDoF_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void OET_Example_multibodyWECSingleDoF_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int OET_Example_multibodyWECSingleDoF_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_checkForAsserts(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int OET_Example_multibodyWECSingleDoF_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* OET_Example_multibodyWECSingleDoF_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* OET_Example_multibodyWECSingleDoF_relationDescription(int i);
extern void OET_Example_multibodyWECSingleDoF_function_initSample(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OET_Example_multibodyWECSingleDoF_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OET_Example_multibodyWECSingleDoF_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OET_Example_multibodyWECSingleDoF_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OET_Example_multibodyWECSingleDoF_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OET_Example_multibodyWECSingleDoF_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OET_Example_multibodyWECSingleDoF_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int OET_Example_multibodyWECSingleDoF_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int OET_Example_multibodyWECSingleDoF_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int OET_Example_multibodyWECSingleDoF_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int OET_Example_multibodyWECSingleDoF_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int OET_Example_multibodyWECSingleDoF_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int OET_Example_multibodyWECSingleDoF_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int OET_Example_multibodyWECSingleDoF_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* OET_Example_multibodyWECSingleDoF_linear_model_frame(void);
extern const char* OET_Example_multibodyWECSingleDoF_linear_model_datarecovery_frame(void);
extern int OET_Example_multibodyWECSingleDoF_mayer(DATA* data, modelica_real** res, short *);
extern int OET_Example_multibodyWECSingleDoF_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int OET_Example_multibodyWECSingleDoF_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int OET_Example_multibodyWECSingleDoF_setInputData(DATA *data, const modelica_boolean file);
extern int OET_Example_multibodyWECSingleDoF_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void OET_Example_multibodyWECSingleDoF_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void OET_Example_multibodyWECSingleDoF_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int OET_Example_multibodyWECSingleDoF_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void OET_Example_multibodyWECSingleDoF_read_simulation_info(SIMULATION_INFO* simulationData);
extern void OET_Example_multibodyWECSingleDoF_read_input_fmu(MODEL_DATA* modelData);
extern void OET_Example_multibodyWECSingleDoF_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int OET_Example_multibodyWECSingleDoF_inputNames(DATA* data, char ** names);
extern int OET_Example_multibodyWECSingleDoF_dataReconciliationInputNames(DATA* data, char ** names);
extern int OET_Example_multibodyWECSingleDoF_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int OET_Example_multibodyWECSingleDoF_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int OET_Example_multibodyWECSingleDoF_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int OET_Example_multibodyWECSingleDoF_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "OET.Example.multibodyWECSingleDoF_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(OET_Example_multibodyWECSingleDoF__MODEL_H) */


