/* Simulation code for quadratic generated by the OpenModelica Compiler OpenModelica v1.24.3 (64-bit). */
#if !defined(quadratic__MODEL_H)
#define quadratic__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "quadratic_functions.h"


extern void quadratic_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void quadratic_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int quadratic_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int quadratic_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int quadratic_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int quadratic_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int quadratic_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int quadratic_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int quadratic_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int quadratic_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int quadratic_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int quadratic_checkForAsserts(DATA *data, threadData_t *threadData);
extern int quadratic_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int quadratic_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int quadratic_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* quadratic_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* quadratic_relationDescription(int i);
extern void quadratic_function_initSample(DATA *data, threadData_t *threadData);
extern int quadratic_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int quadratic_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int quadratic_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int quadratic_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int quadratic_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int quadratic_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int quadratic_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int quadratic_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int quadratic_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int quadratic_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int quadratic_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int quadratic_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int quadratic_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int quadratic_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* quadratic_linear_model_frame(void);
extern const char* quadratic_linear_model_datarecovery_frame(void);
extern int quadratic_mayer(DATA* data, modelica_real** res, short *);
extern int quadratic_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int quadratic_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int quadratic_setInputData(DATA *data, const modelica_boolean file);
extern int quadratic_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void quadratic_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void quadratic_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int quadratic_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void quadratic_read_simulation_info(SIMULATION_INFO* simulationData);
extern void quadratic_read_input_fmu(MODEL_DATA* modelData);
extern void quadratic_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int quadratic_inputNames(DATA* data, char ** names);
extern int quadratic_dataReconciliationInputNames(DATA* data, char ** names);
extern int quadratic_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int quadratic_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int quadratic_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int quadratic_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "quadratic_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(quadratic__MODEL_H) */


