/* Simulation code for inerter generated by the OpenModelica Compiler OpenModelica v1.24.3 (64-bit). */
#if !defined(inerter__MODEL_H)
#define inerter__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "inerter_functions.h"

#define Modelica_Math_Vectors_length_index 0
#define Modelica_Math_Vectors_normalize_index 1
#define Modelica_Mechanics_MultiBody_Frames_Orientation_index 2
#define Modelica_Mechanics_MultiBody_Frames_resolve2_index 3
#define Modelica_Mechanics_MultiBody_Frames_TransformationMatrices_from__nxy_index 4

extern void inerter_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void inerter_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int inerter_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int inerter_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int inerter_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int inerter_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int inerter_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int inerter_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int inerter_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int inerter_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int inerter_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int inerter_checkForAsserts(DATA *data, threadData_t *threadData);
extern int inerter_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int inerter_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int inerter_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* inerter_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* inerter_relationDescription(int i);
extern void inerter_function_initSample(DATA *data, threadData_t *threadData);
extern int inerter_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int inerter_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int inerter_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int inerter_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int inerter_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int inerter_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int inerter_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int inerter_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int inerter_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int inerter_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int inerter_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int inerter_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int inerter_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int inerter_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* inerter_linear_model_frame(void);
extern const char* inerter_linear_model_datarecovery_frame(void);
extern int inerter_mayer(DATA* data, modelica_real** res, short *);
extern int inerter_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int inerter_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int inerter_setInputData(DATA *data, const modelica_boolean file);
extern int inerter_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void inerter_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void inerter_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int inerter_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void inerter_read_simulation_info(SIMULATION_INFO* simulationData);
extern void inerter_read_input_fmu(MODEL_DATA* modelData);
extern void inerter_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int inerter_inputNames(DATA* data, char ** names);
extern int inerter_dataReconciliationInputNames(DATA* data, char ** names);
extern int inerter_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int inerter_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int inerter_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int inerter_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "inerter_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(inerter__MODEL_H) */


