/* Additional record code for inerter_test3 generated by the OpenModelica Compiler OpenModelica v1.24.3 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "inerter_test3_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Modelica_Mechanics_MultiBody_Frames_Orientation__desc_added 1
const char* Modelica_Mechanics_MultiBody_Frames_Orientation__desc__fields[2] = {"T","w"};
struct record_description Modelica_Mechanics_MultiBody_Frames_Orientation__desc = {
  "Modelica_Mechanics_MultiBody_Frames_Orientation", /* package_record__X */
  "Modelica.Mechanics.MultiBody.Frames.Orientation", /* package.record_X */
  Modelica_Mechanics_MultiBody_Frames_Orientation__desc__fields
};

void Modelica_Mechanics_MultiBody_Frames_Orientation_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Mechanics_MultiBody_Frames_Orientation* ths = (Modelica_Mechanics_MultiBody_Frames_Orientation*)(v_ths);
  alloc_real_array(&(ths->_T), 2, (_index_t)3, (_index_t)3); // ths->_T has no default value.
  alloc_real_array(&(ths->_w), 1, (_index_t)3); // ths->_w has no default value.
}
void Modelica_Mechanics_MultiBody_Frames_Orientation_wrap_vars_p(threadData_t *threadData, void* v_dst , real_array in_T, real_array in_w) {
  Modelica_Mechanics_MultiBody_Frames_Orientation* dst = (Modelica_Mechanics_MultiBody_Frames_Orientation*)(v_dst);
  dst->_T = in_T;
  dst->_w = in_w;
}

void Modelica_Mechanics_MultiBody_Frames_Orientation_copy_p(void* v_src, void* v_dst) {
  Modelica_Mechanics_MultiBody_Frames_Orientation* src = (Modelica_Mechanics_MultiBody_Frames_Orientation*)(v_src);
  Modelica_Mechanics_MultiBody_Frames_Orientation* dst = (Modelica_Mechanics_MultiBody_Frames_Orientation*)(v_dst);
  real_array_copy_data(src->_T, dst->_T);
  real_array_copy_data(src->_w, dst->_w);
}

#ifdef __cplusplus
}
#endif

